### ISSUE TITLE
`npm test` failed

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE-vscode#469]
I got the following error when I run `run test`. Can someone help me?

```
$ git log -2 --oneline 
9dcb26f (HEAD -> main, upstream/main, upstream/HEAD) Add basic support for multiple backend (#451)
f59f670 (9002-format) [Compiler/View] Add refresh button (#446)

$ npm test

> one-vscode@0.0.1 pretest
> npm run compile && npm run lint && npm run lintjs && npm run lintcss && npm run linthtml

> one-vscode@0.0.1 compile
> tsc -p ./

...

> one-vscode@0.0.1 test
> npm run unittest

> one-vscode@0.0.1 unittest
> node ./out/Tests/runTest.js

Downloading VS Code 1.66.1 from https://update.code.visualstudio.com/1.66.1/linux-x64/stable
Downloading VS Code [=============================-] 98%Downloaded VS Code 1.66.1 into /home/eric/m/work/3/ONE-vscode/.vscode-test/vscode-linux-x64-1.66.1
Downloading VS Code [==============================] 100%
[0411/192224.513935:ERROR:directory_reader_posix.cc(42)] opendir /home/eric/m/work/3/ONE-vscode/.vscode-test/user-data/Crashpad/attachments/24672de7-e4be-4ad4-bd7b-5b86b91ac486: No such file or directory (2)
Exit code:   SIGTRAP
Failed to run tests
```

FYI, I got error if I run "Extension Tests" in Debug screen of vscode. I am not sure if the above error is related to error below.
```
...
[0m  3) Utils
       Helpers
         #obtainWorkspaceRoot()
           returns workspaceRoot as string:
[0m[31m     Error: Need workspace[0m[90m
  	at obtainWorkspaceRoot (m/work/3/ONE-vscode/out/Utils/Helpers.js:55:15)
  	at Context.<anonymous> (m/work/3/ONE-vscode/out/Tests/Utils/Helpers.test.js:25:73)
  	at processImmediate (node:internal/timers:464:21)
  	at process.callbackTrampoline (node:internal/async_hooks:130:17)
[0m

[0m  4) Utils
       Helpers
         #loadCfgFile()
           returns cfgIni object:
[0m[31m     Error: Need workspace[0m[90m
  	at obtainWorkspaceRoot (m/work/3/ONE-vscode/out/Utils/Helpers.js:55:15)
  	at Context.<anonymous> (m/work/3/ONE-vscode/out/Tests/Utils/Helpers.test.js:32:73)
  	at processImmediate (node:internal/timers:464:21)
  	at process.callbackTrampoline (node:internal/async_hooks:130:17)
[0m
...
```

**Comment by YongseopKim** [comment]
And, the below error looks not the same to the above thing.

**Comment by hyunsik-yoon** [comment]
I still got the error after running `npm run clean`.
I will google the reason.

<details>

```shell
eric@labs:~/m/work/4/ONE-vscode  ( git: main) (11:44:37)
$ git log -2 --oneline 
9dcb26f (HEAD -> main, upstream/main, upstream/HEAD) Add basic support for multiple backend (#451)
f59f670 [Compiler/View] Add refresh button (#446)

eric@labs:~/m/work/4/ONE-vscode  ( git: main) (11:44:46)
$ git status
On branch main
Your branch is up to date with 'upstream/main'.

nothing to commit, working tree clean

eric@labs:~/m/work/4/ONE-vscode  ( git: main) (11:44:48)
$ npm run clean

> one-vscode@0.0.1 clean
> rm -rf out

eric@labs:~/m/work/4/ONE-vscode  ( git: main) (11:44:48)
$ npm test
 ...

style.css
69: warning at line 307, col 3
Expected (<color>) but found 'var(--vscode-badge-foreground)'.
  color: var(--vscode-badge-foreground);

style.css
70: warning at line 308, col 3
Expected (<color>) but found 'var(--vscode-badge-background)'.
  background-color: var(--vscode-badge-background);

> one-vscode@0.0.1 linthtml
> htmlhint media src


Scanned 3 files, no errors found (34 ms).

> one-vscode@0.0.1 test
> npm run unittest


> one-vscode@0.0.1 unittest
> node ./out/Tests/runTest.js

Found existing install in /home/eric/m/work/3/ONE-vscode/.vscode-test/vscode-linux-x64-1.66.1. Skipping download
[0412/114529.004952:ERROR:directory_reader_posix.cc(42)] opendir /home/eric/m/work/3/ONE-vscode/.vscode-test/user-data/Crashpad/attachments/72c9636a-3bb7-44bf-9383-7b62c1baef3b: No such file or directory (2)
Exit code:   SIGTRAP
Failed to run tests
```

</details>

**Comment by hyunsik-yoon** [comment]
> ERROR:directory_reader_posix.cc(42)] opendir /home/eric/m/work/4/ONE-vscode/.vscode-test/user-data/Crashpad/attachments/17340890-5585-4f28-bb9b-c1359855c5d3: No such file or directory (2)

I tried `$ mv .vscode-test .vscode-test-old && npm teset` but got same error.

**Comment by YongseopKim** [comment]
T-T I got the same error now. I'm investigating.
